### Single coin change
# This test case checks if the API correctly returns the fewest number of coins for a target of 25 cents.
# The available coins are 1, 5, 10, 25, and 100 cents. The expected result is a single 25 cent coin.

POST {{host}}/api/change HTTP/1.1
Content-Type: application/json

{
  "coins": [
    1,
    5,
    10,
    25,
    100
  ],
  "target": 25
}

> {%
    client.test("Single coin change", function () {
        client.assert(response.status === 200, "Response status is not 200");
        const type = response.contentType.mimeType;
        client.assert(type === "application/json", `Expected 'application/json' but received '${type}'`);
        let body = response.body;
        client.assert(body.fewestCoins.length === 1, "Number of coins is not 1");
        client.assert(body.fewestCoins[0] === 25, "The coin is not 25 cents");
    })
%}
