name: httpYac Simple Assertions

on:
  workflow_dispatch:
permissions:
  contents: read
  actions: read
  checks: write
  issues: read
  pull-requests: write
jobs:
  run_httpyac_api_tests:
    name: httpYac Simple Assertions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies and run tests
        run: |
          npm install
          npm run httpyac
