name: httpYac Simple Assertions

on:
  workflow_dispatch:
permissions:
  contents: read
  actions: read
  checks: write
  issues: read
  pull-requests: write
jobs:
  run_httpyac_api_tests:
    name: httpYac Simple Assertions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies and run tests
        run: |
          npm install
          npm run httpyac

      - name: Publish Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: httpYac API Tests (Report dorny)
          path: report.xml
          reporter: java-junit

      - name: Publish API Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          check_name: httpYac API Tests (Report EnricoMi)
          junit_files: report.xml